networks:
  inception:
    name: inception
    driver: bridge
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/adanylev/data/mysql"
      o: bind
      type: none

  wordpress_data:
    driver: local
    driver_opts:
      device: "/home/adanylev/data/wordpress"
      o: bind
      type: none
