
services:
        nginx:
                build: ./requirements/nginx      
                container_name: nginx
                restart: always
                ports:
                        - "443:443"
                volumes:
                        - wp_files:/var/www/html
                networks:
                        - inception
                depends_on:
                        - mariadb

        mariadb:
                build: ./requirements/mariadb
                container_name: mariadb
                restart: always
                volumes:
                        - mariadb_data:/var/lib/mysql
                env_file:
                        - .env
                networks:
                        - inception


volumes:
        wp_files: {} 
        mariadb_data: {}
networks:
        inception:
                driver: bridge
