
services:
        nginx:
                build: ./requirements/nginx      
                container_name: nginx
                restart: always
                ports:
                        - "443:443"
                volumes:
                        - wp_files:/var/www/html
                networks:
                        - inception

volumes:
        wp_files: {} 

networks:
        inception:
                driver: bridge
